spring.application.name=newapp
server.port=8081
spring.thymeleaf.cache=false

# ERPNext Configuration
erpnext.api.url=http://erpnext.localhost:8000

# Logging Configuration
logging.level.com.example.newapp=DEBUG
logging.level.org.springframework.web=DEBUG

# Configuration du multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
