spring.application.name=newapp
server.port=8081
spring.thymeleaf.cache=false

# ERPNext Configuration
erpnext.api.url=http://erpnext.localhost:8000
erpnext.api.username=Administrator
erpnext.api.password=popo1234

# Logging Configuration
logging.level.com.example.newapp=DEBUG
logging.level.org.springframework.web=DEBUG
