dbfilename redis_queue.rdb
dir /mnt/d/itu/L3/S6/Eval2/erp/config/pids
pidfile /mnt/d/itu/L3/S6/Eval2/erp/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /mnt/d/itu/L3/S6/Eval2/erp/config/redis_queue.acl
